# Install: sudo apt install python3-pytest
# Usage: pytest -m testsubmodule -s a_file.py or pytest -m testsubmodule -k test_function_name path/to/file.py. When you want to run with logging, add `--log-cli-level=DEBUG`


[pytest]
addopts = -s --log-cli-level=DEBUG
# testpaths = .
python_files = test_*.py *_test.py
# python_classes = Test*
python_functions = test_*
markers =
    testsubmodule: only test for submodules function
    ds: tests that access the dataset

